FROM envoyproxy/envoy:contrib-v1.34.1
ENV GO_VERSION="https://go.dev/dl/go1.24.4.linux-arm64.tar.gz"
ENV GOBIN="/go/bin"
ENV PATH="${PATH}:${GOBIN}:/usr/local/go/bin"
ENV GOPATH="/go"
WORKDIR /go/src
RUN apt -y update \
    && apt -y install \
      libxml2-dev \
      libyajl-dev \
      libgeoip-dev \
      libcurl4-openssl-dev \
      gcc \
      vim \
      wget
RUN wget $GO_VERSION \
    && tar -C /usr/local -xzf go1.24.4.linux-arm64.tar.gz \
    && rm go1.24.4.linux-arm64.tar.gz \
    && mkdir -p /go/bin \
    && go install github.com/go-delve/delve/cmd/dlv@latest
COPY /config/ /config/
COPY include/ /usr/local/include/
COPY libwafie.so /usr/local/lib/libwafie.so
RUN ldconfig

