name: Build and Upload to Github artifacts
on:
  push:
    branches:
      - main
jobs:
  build:
    if: contains(github.event.head_commit.message, '[build-docker]')
    name: Build wafie lib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dimssss/modsec:latest
          platforms: linux/${{ matrix.architecture }}
